apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: david
  description: david
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: david.stewart@harness.io
  lifecycle: experimental
